name: 'Bytebase Create Plan From Release'
description: 'Create a plan from release on Bytebase.'

branding:
  icon: 'database'
  color: 'red'

inputs:
  url:
    description: The bytebase URL.
    required: true
  token:
    description: The Bytebase access token.
    required: true
  project:
    description: 'The project on Bytebase. Format: projects/{project}'
    required: true
  release:
    description:
      'The release to create plan from. Format:
      projects/{project}/releases/{release}'
    required: true
  targets:
    description: >
      The database group or databases to deploy. Either a comma separated list
      of the databases or a database group. Databases example:
      `instances/mysql1/databases/db1,instances/mysql1/databases/db2`. Database
      format: instances/{instance}/databases/{database} Database group example:
      `projects/exa/databaseGroups/mygroup` Database group format:
      projects/{project}/databaseGroups/{databaseGroup}
    required: true
  check-plan:
    description: >
      An enum to determine should we run plan checks and fail on warning or
      error. Valid values are `SKIP`, `FAIL_ON_WARNING`, `FAIL_ON_ERROR`
    default: SKIP

outputs:
  plan:
    description: 'The created plan. Format: projects/{project}/plans/{plan}'

runs:
  using: node20
  main: dist/index.js
